### ISSUE TITLE
Consolidate httpClient and apiService implementations

### ISSUE THREAD

**Issue by dschmidt** [metadist/synaplan#178]
## Problem

We currently have two HTTP client implementations that are unclear and duplicated:

1. **`/frontend/src/services/api/httpClient.ts`** - Modern implementation with:
   - Cookie-based authentication
   - Automatic token refresh on 401
   - OIDC session handling
   - Schema validation support (Zod)
   - Multiple response types (json, blob, text, arrayBuffer)

2. **`/frontend/src/services/apiService.ts`** - Contains its own `httpClient` function with:
   - Cookie-based authentication
   - CSRF token handling
   - Request timeout
   - Schema validation support (Zod) - recently added
   - Comment says "prefer using @/services/api/httpClient instead"

## Issues

- **Duplication**: Two implementations with overlapping functionality
- **Confusion**: Not clear which one to use when
- **Maintenance burden**: Bug fixes and features need to be implemented twice
- **Inconsistent behavior**: The two implementations handle auth and errors differently
  - apiService redirects to login immediately on 401
  - httpClient has sophisticated token refresh logic

## Current Usage

Both are actively used throughout the codebase:
- New API files (`chatApi.ts`, `widgetsApi.ts`, `authApi.ts`, etc.) use the modern httpClient
- `apiService` exports methods like `fetchAvailableModels`, `verifyEmail`, etc.
- `apiService` also exports an axios-like `api` object with `.get`, `.post`, `.delete` methods

## Proposed Solution

1. **Audit usage**: Map out which files use which implementation
2. **Standardize on one**: Likely the modern `httpClient` from `/services/api/httpClient.ts` as it has better auth handling
3. **Migration plan**: 
   - Move `apiService` methods to dedicated API modules (e.g., `configApi.ts`, `authApi.ts`)
   - Update the axios-like `api` object wrapper to use the modern httpClient
   - Remove duplicate httpClient from apiService
4. **Documentation**: Clear guidelines on when and how to use the HTTP client

## Benefits

- Single source of truth for HTTP requests
- Consistent error handling and auth across the app
- Easier maintenance and testing
- Clear patterns for developers

**Comment by orgaralf** [comment]
not valid anymore, was fixed by version change

**Comment by FExB17** [comment]
Reopened after audit of the 2026-06-30 AI cleanup: closed with generic comment "not valid anymore, was fixed by version change" but the underlying problem is still present in `main` (verified 2026-07-02). See team audit notes.

**Comment by dschmidt** [comment]
@FExB17 ? :D
